version: '3.8'

services:
  # Stokio - Aplicação Principal
  stokio:
    image: ${DOCKERHUB_USERNAME:-martelr}/stok.io:latest
    container_name: stokio_app
    restart: always
    expose:
      - "3000"
    networks:
      - traefik_network
    labels:
      - "traefik.enable=true"
      # Ajuste o Host para o domínio principal do seu servidor de produção
      - "traefik.http.routers.stokio.rule=Host(`${DOMAIN:-stok.io}`)"
      - "traefik.http.routers.stokio.entrypoints=websecure"
      - "traefik.http.routers.stokio.tls.certresolver=myresolver"
      - "traefik.http.services.stokio.loadbalancer.server.port=3000"
      # Watchtower para auto-atualização
      - "com.centurylinklabs.watchtower.enable=true"

  # O Atualizador Automático (Watchtower)
  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - WATCHTOWER_CLEANUP=true
      - WATCHTOWER_POLL_INTERVAL=60
      - WATCHTOWER_INCLUDE_RESTARTING=true
      - WATCHTOWER_LABEL_ENABLE=true
    restart: always

networks:
  traefik_network:
    external: true
