version: '3.8'

services:
  # Stokio - Sua Aplicação Next.js
  stokio:
    # Usamos a imagem pré-construída no GitHub Actions
    image: ${DOCKERHUB_USERNAME:-martelr}/stok.io:latest
    container_name: stokio_app
    restart: always
    # Não precisamos mais do bloco build no servidor de produção, 
    # mas mantemos comentado caso queira buildar localmente
    # build:
    #   context: .
    #   dockerfile: Dockerfile
    #   args:
    #     - NEXT_PUBLIC_FIREBASE_API_KEY=${NEXT_PUBLIC_FIREBASE_API_KEY}
    #     ...
    expose:
      - "3000"
    labels:
      - "com.centurylinklabs.watchtower.enable=true"

  # O Túnel Cloudflare
  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: cloudflared_tunnel
    command: tunnel run
    environment:
      - TUNNEL_TOKEN=${TUNNEL_TOKEN}
    restart: always
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    depends_on:
      - stokio

  # O Atualizador Automático (Watchtower)
  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - WATCHTOWER_CLEANUP=true
      - WATCHTOWER_POLL_INTERVAL=60 # Verifica a cada 60 segundos
      - WATCHTOWER_INCLUDE_RESTARTING=true
      - WATCHTOWER_LABEL_ENABLE=true # Só atualiza containers com a label enable=true
    restart: always