name: Deploy no Servidor via Pull

on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: Deploy no Servidor
    runs-on: ubuntu-latest
    steps:
      - name: Conectar e Fazer Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /opt/stok.io/
            git pull origin master
            docker-compose down
            docker-compose up -d --build
            docker image prune -af